version: '3.8'
services:
  go-api1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    command: "./api1/main"
    environment:
      - LOG_FILE=/app/logs/app.log
    volumes:
      - shared-logs:/app/logs

  go-api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    command: "./api2/main"
    environment:
      - LOG_FILE=/app/logs/app.log
    volumes:
      - shared-logs:/app/logs

  go-api3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    command: "./api3/main"
    environment:
      - LOG_FILE=/app/logs/app.log
    volumes:
      - shared-logs:/app/logs

  go-api4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - mynetwork
    command: "./api4/main"
    environment:
      - LOG_FILE=/app/logs/app.log
    volumes:
      - shared-logs:/app/logs
    
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    container_name: jaeger  
    ports:
      - "16686:16686"
      - "14268:14268"
    depends_on:
      - go-api1
    networks:
      - mynetwork
  
  splunk:
    image: splunk/splunk:8.0
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_ADD=monitor /app/logs
      - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      splunk:
        condition: service_healthy
    volumes:
      - shared-logs:/app/logs
    networks:
      - mynetwork

  telegraf:
    image: telegraf:1.8
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - splunk
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  shared-logs:
    driver: local
    driver_opts:
      type: none
      device: /Users/dhiren.singh/Desktop/var/logs
      o: bind
